jobs:
  - name: u16golalltesting
    type: runSh
    steps:
      - TASK:
          runtime:
            options:
              imageName: "drydock/u16golall"
              imageTag: master
          script:
             - source $HOME/.gvm/scripts/gvm
             - gvm list
             
              
